CREATE DATABASE PRUEBA_TECNICA_TBTB;
USE PRUEBA_TECNICA_TBTB;

CREATE TABLE USERS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    REGISTER_DATE DATETIME DEFAULT GETDATE(),
    ROLE_ID INT,
    STATUS BIT DEFAULT 1,
    CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE ROLES (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) UNIQUE NOT NULL,
    STATUS BIT DEFAULT 1
);

CREATE TABLE ACCESS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) UNIQUE NOT NULL,
    STATUS BIT DEFAULT 1
);

CREATE TABLE ACCESS_BY_ROLE (
    ROLE_ID INT NOT NULL,
    ACCESS_ID INT NOT NULL,
    PRIMARY KEY (ROLE_ID, ACCESS_ID),
    CONSTRAINT FK_ACCESS_BY_ROLE_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
    CONSTRAINT FK_ACCESS_BY_ROLE_ACCESS FOREIGN KEY (ACCESS_ID) REFERENCES ACCESS(ID)
);

INSERT INTO ROLES (NAME, STATUS) VALUES ('Administrador', 1); 
INSERT INTO ROLES (NAME, STATUS) VALUES ('Usuario', 1); 
INSERT INTO ROLES (NAME, STATUS) VALUES ('Gerente', 1); 
INSERT INTO ROLES (NAME, STATUS) VALUES ('Desarrollador', 1); 
INSERT INTO ROLES (NAME, STATUS) VALUES ('Invitado', 1); 

INSERT INTO ACCESS (NAME, STATUS) VALUES ('Leer', 1);
INSERT INTO ACCESS (NAME, STATUS) VALUES ('Escribir', 1); 
INSERT INTO ACCESS (NAME, STATUS) VALUES ('Ejecutar', 1);
INSERT INTO ACCESS (NAME, STATUS) VALUES ('Eliminar', 1);
INSERT INTO ACCESS (NAME, STATUS) VALUES ('Actualizar', 1); 

INSERT INTO USERS (NAME, EMAIL, ROLE_ID, STATUS) VALUES ('Carlos Martínez', 'carlos.martinez@example.com', 1, 1); 
INSERT INTO USERS (NAME, EMAIL, ROLE_ID, STATUS) VALUES ('Ana Pérez', 'ana.perez@example.com', 2, 1);
INSERT INTO USERS (NAME, EMAIL, ROLE_ID, STATUS) VALUES ('Javier Gómez', 'javier.gomez@example.com', 3, 1);
INSERT INTO USERS (NAME, EMAIL, ROLE_ID, STATUS) VALUES ('María Rodríguez', 'maria.rodriguez@example.com', 4, 1);
INSERT INTO USERS (NAME, EMAIL, ROLE_ID, STATUS) VALUES ('Luis González', 'luis.gonzalez@example.com', 5, 1); 

INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (1, 1); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (1, 2); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (1, 3); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (2, 1); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (2, 4); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (3, 1); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (3, 2);
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (3, 3); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (4, 1); 
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (4, 2);
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (4, 5);
INSERT INTO ACCESS_BY_ROLE (ROLE_ID, ACCESS_ID) VALUES (5, 1); 
