USE PRUEBA_TECNICA_TBTB;

-- INNER JOIN
SELECT R.NAME AS ROL, A.NAME AS ACCESO
FROM ACCESS_BY_ROLE ABR
INNER JOIN ROLES R ON ABR.ROLE_ID = R.ID
INNER JOIN ACCESS A ON ABR.ACCESS_ID = A.ID;

SELECT U.NAME AS NOMBRE, U.EMAIL AS CORREO, R.NAME AS ROL
FROM USERS U
INNER JOIN ROLES R ON U.ROLE_ID = R.ID;

-- LEFT JOIN
SELECT U.NAME AS NOMBRE, U.EMAIL AS CORREO, R.NAME AS ROL
FROM USERS U
LEFT JOIN ROLES R ON U.ROLE_ID = R.ID;

SELECT R.NAME AS RoleName, A.NAME AS AccessName
FROM ROLES R
LEFT JOIN ACCESS_BY_ROLE ABR ON R.ID = ABR.ROLE_ID
LEFT JOIN ACCESS A ON ABR.ACCESS_ID = A.ID;

-- UNION
SELECT NAME FROM ROLES
UNION
SELECT NAME FROM ACCESS;

SELECT NAME FROM USERS
UNION
SELECT EMAIL FROM USERS
UNION
SELECT NAME FROM ROLES
UNION
SELECT NAME FROM ACCESS;

-- CASE
SELECT NAME, EMAIL,
       CASE 
           WHEN STATUS = 1 THEN 'Activo'
           ELSE 'Inactivo'
       END AS StatusDescription
FROM USERS;

SELECT NAME,
       CASE 
           WHEN STATUS = 1 THEN 'Activo'
           ELSE 'Inactivo'
       END AS StatusDescription
FROM ROLES;

  -- INSERT IN USERS
CREATE PROCEDURE sp_insert_user
@NAME VARCHAR(100),
@EMAIL VARCHAR(100),
@ROLE_ID INT
AS
BEGIN
 INSERT INTO [USERS] ([NAME],[EMAIL],[ROLE_ID]) VALUES (@NAME, @EMAIL, @ROLE_ID)
END



-- SELECT FROM USERS
CREATE PROCEDURE sp_list_users
AS
BEGIN
      SELECT U.[ID],U.[NAME],U.[EMAIL],U.[REGISTER_DATE],U.STATUS, R.ID AS ID_ROL,R.NAME AS NAME_ROL, R.STATUS AS STATUS_ROL
	  FROM [PRUEBA_TECNICA_TBTB].[dbo].[USERS] U
	  INNER JOIN ROLES R ON U.ROLE_ID = R.ID
END


-- UPDATE USER
CREATE PROCEDURE sp_update_user
@ID INT,
@NAME VARCHAR(100),
@EMAIL VARCHAR(100),
@ROLE_ID INT,
@STATUS BIT
AS
BEGIN
 UPDATE USERS SET NAME = @NAME, EMAIL = @EMAIL, ROLE_ID = @ROLE_ID, STATUS = @STATUS WHERE ID = @ID
END


-- DELETE
CREATE PROCEDURE sp_delete_user
@ID INT
AS
BEGIN
 DELETE FROM USERS WHERE ID = @ID
END


EXEC sp_list_users
EXEC sp_insert_user 'Daniel Hincapie', 'dhincapie087@gmail.com', 1
EXEC sp_update_user 6, 'Daniel Hincapie', 'dhincapie087@gmail.com',2, 1
EXEC sp_delete_user 6